import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import { Suspense } from "react";

import { ThemeProvider } from "@/components/theme-provider"
import DesktopNavigation from "@/components/desktop-navigation";
import MobileNavigation from "@/components/mobile-navigation";

import { cn } from "@/lib/utils";
import { Toaster } from "sonner";
import "../assets/globals.css";
import ModeToggle from "@/components/mode-toggle";
import Link from "next/link";
import Loading from "./loading";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(
        fontSans.variable,
        "antialiased flex flex-col min-h-screen",
      )}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <header className="w-full border-b top-0 bg-background z-50">
              <div className="width-regulator">
                <DesktopNavigation />
                <MobileNavigation />
              </div>
            </header>
            <main className="flex-grow">
              <Suspense fallback={<Loading />}>
                <div className="my-10 px-4">
                  {children}
                </div>
                <Toaster expand richColors pauseWhenPageIsHidden  />
              </Suspense>
            </main>
            <footer className="text-accent-foreground border-t w-full px-6">
              <div className="width-regulator py-6">
                <div className="flex justify-between items-center text-sm gap-4">
                  <div className="flex-shrink-0 max-md:text-center">
                    Davs &#x30C4;
                  </div>
                  <div className="flex items-center max-md:justify-center gap-4">
                    <div className="md:hidden">
                      <ModeToggle />
                    </div>
                    <div className="max-md:hidden">
                      <p>
                        Source on <Link target="_blank" className="underline" href="https://github.com/d4vss/portfolio-page">GitHub</Link>
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </footer>
          </ThemeProvider>
      </body>
    </html>
  );
}
