name: Deploy to Docker

on:
  push:
    branches:
      - main

jobs:
  build-project:
    name: Build project
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t portfolio-page .

      - name: Deploy Docker container
        if: success()
        run: |
          docker stop portfolio-page || true
          docker rm portfolio-page || true
          docker run -d -p 3001:3000 \
            --name portfolio-page \
            --restart unless-stopped \
            portfolio-page

      - name: Remove unused Docker images
        if: success()
        run: |
          docker image prune -f
