name: Deploy to Docker

on:
  push:
    branches:
      - main

jobs:
  build-project:
    name: Build project
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "NEXT_PUBLIC_TURNSTILE_SITE_KEY=${{ secrets.NEXT_PUBLIC_TURNSTILE_SITE_KEY }}" >> .env
          echo "NEXT_PRIVATE_TURNSTILE_SECRET_KEY=${{ secrets.NEXT_PRIVATE_TURNSTILE_SECRET_KEY }}" >> .env
          echo "DISCORD_WEBHOOK_URL=${{ secrets.DISCORD_WEBHOOK_URL }}" >> .env
          echo "AUTH_TRUST_HOST=TRUE" >> .env      

      - name: Build Docker image
        run: |
          docker build -t portfolio .

      - name: Deploy Docker container
        if: success()
        run: |
          docker stop portfolio || true
          docker rm portfolio || true
          docker run -d -p 3001:3000 \
            --name portfolio \
            --restart unless-stopped \
            portfolio

      - name: Cleanup
        run: |
          rm .env

      - name: Remove unused Docker images
        run: |
          docker image prune -f